/* Things moving behind the wallpaper.
 *
 * Short grayscale clips (generated by tools/blender/wall_apparitions.py) of
 * hands and screaming faces pressing through a membrane. They are spawned at
 * random positions, at random size and intensity, and removed when they finish.
 *
 * Two things make this work, both of which are easy to break:
 *
 * 1. BLENDING. The clips have no alpha channel. They are centred on neutral
 *    grey -- flat wall is exactly 50% grey, relief swings above and below it --
 *    and `mix-blend-mode: soft-light` leaves a neutral source untouched. So the
 *    rectangles vanish and the apparitions only brighten or darken the
 *    wallpaper in its own colour, rather than adding pale light on top of it.
 *    The blend lives on the *container*, not just the clips: a fixed-position
 *    element establishes a stacking context, so children blend into that group
 *    rather than into the page, and the group's own blend is what reaches the
 *    wallpaper.
 *
 * 2. PAINT ORDER. The layer sits after .wall but before .stage. Soft-light is
 *    multiplicative, so blending it under .wall against the near-black body
 *    background produced nothing visible; it has to blend over the burgundy
 *    itself. Because soft-light preserves backdrop detail, the damask weave
 *    still reads through the bulges and gets shaded by them. Giving this
 *    element a z-index, or moving it past .stage, breaks one or the other.
 */

/* Weighted rather than uniform, so the mix is a decision rather than a side
 * effect of how many clips of each kind happen to exist.
 *
 * Faces run about two to one over hands. Weighting them equally across five
 * face clips is what makes that affordable: a face is a still pose and repeats
 * are conspicuous, so the extra frequency has to be spread over the whole set
 * rather than concentrated, or the wall just shows the same scream more often.
 * face-hands is counted on the hand side -- it is the widest clip in the
 * library and reads as a hands clip that happens to contain a head. */
const CLIPS = [
  { name: 'face-a', w: 512, h: 512, weight: 3 },
  { name: 'face-b', w: 512, h: 512, weight: 3 },
  { name: 'face-c', w: 512, h: 512, weight: 3 },
  { name: 'face-d', w: 512, h: 512, weight: 3 },
  { name: 'face-e', w: 512, h: 512, weight: 3 },
  { name: 'hand-a', w: 448, h: 512, weight: 3 },
  { name: 'hand-b', w: 448, h: 512, weight: 3 },
  { name: 'hands-pair', w: 768, h: 480, weight: 1 },
  { name: 'face-hands', w: 832, h: 512, weight: 1 },
];

/* Intensity tiers, weighted. Most apparitions are meant to be missable -- the
 * effect works by making you doubt you saw it, and a wall of confident faces
 * stops being unsettling very quickly. */
/* Opacities run high because soft-light is a gentle blend over a wall this
 * dark -- these are nothing like the values screen blending wanted.
 *
 * Blur is for hiding compression and upscaling, and that is all it is for. It
 * used to run to 10px on the commonest tier, on the theory that blurrier meant
 * more missable; what it actually reads as is a thick, diffusing wall, which is
 * the opposite of something pressing through taut fabric. Subtlety comes from
 * opacity. Keep these low enough that the relief the renderer works so hard to
 * resolve still arrives on screen. */
/* The floor matters more than the ceiling here. The faintest tier is also the
 * commonest, so where it lands is what the wall looks like most of the time --
 * and down at 0.32 it was a stain you had to already know about. The tiers
 * still read as three distinct strengths, they just all press in now. */
const TIERS = [
  { weight: 4, opacity: [0.50, 0.64], blur: [3, 5], height: [22, 30] },
  { weight: 4, opacity: [0.68, 0.84], blur: [2, 3.5], height: [26, 36] },
  { weight: 2, opacity: [0.90, 1.00], blur: [0.6, 1.6], height: [32, 44] },
];

const KEEP_OUT = ['.masthead', '.top-nav', '.shelf-wrap'];
const KEEP_OUT_PAD = 12;
const KEEP_OUT_FEATHER = 26; // px of blur on the mask holes

/* The rendered subject never fills its frame -- there is deliberate margin so
 * the drape can fall off to black. Scoring the full video box would count that
 * empty margin as solid and rule out most of the usable wall. */
const CORE = 0.76;

/* Apparitions may hang off the edge of the viewport by this fraction of their
 * size. The page content leaves only narrow strips of bare wall, and a hand
 * pressing through half-out of frame is both more usable and more unsettling
 * than one politely centred in a gap. */
const BLEED = 0.35;

/* Give up on a spawn whose best available spot is still mostly buried under
 * page content. The mask would hide it anyway; better to skip and try later. */
const MAX_COVERAGE = 0.6;

const SPAWN_MIN = 3000;
const SPAWN_MAX = 7000;

/* An apparition is alive for about 8s -- a 6s clip plus the fade either side --
 * so at this interval one to two are typically on the wall at once. The cap is
 * a burst limiter, and it has to sit clear of that average or it stops being a
 * limiter and quietly becomes the spawn rate. */
const MAX_LIVE = 4;
const PLACE_ATTEMPTS = 40;

const rand = ([lo, hi]) => lo + Math.random() * (hi - lo);

/* Weighted choice over anything carrying a .weight. The trailing return is for
 * floating-point drift on the last item, not for an empty list. */
function pick(items) {
  const total = items.reduce((s, t) => s + t.weight, 0);
  let r = Math.random() * total;
  for (const t of items) if ((r -= t.weight) < 0) return t;
  return items[items.length - 1];
}

function keepOutRects() {
  const rects = [];
  for (const sel of KEEP_OUT) {
    for (const el of document.querySelectorAll(sel)) {
      const r = el.getBoundingClientRect();
      if (r.width > 0 && r.height > 0) rects.push(r);
    }
  }
  return rects;
}

/* Fraction of `box` covered by the protected regions. */
function coverage(box, rects) {
  const area = (box.right - box.left) * (box.bottom - box.top);
  if (area <= 0) return 1;
  let covered = 0;
  for (const r of rects) {
    const w = Math.min(box.right, r.right + KEEP_OUT_PAD) - Math.max(box.left, r.left - KEEP_OUT_PAD);
    const h = Math.min(box.bottom, r.bottom + KEEP_OUT_PAD) - Math.max(box.top, r.top - KEEP_OUT_PAD);
    if (w > 0 && h > 0) covered += w * h;
  }
  // Overlapping protected rects double-count, hence the clamp. Good enough:
  // this only has to rank candidate spots against each other.
  return Math.min(1, covered / area);
}

/* Best of N random spots rather than first-fit.
 *
 * First-fit was the original design and it failed outright: at 1280x720 the
 * masthead, shelf and nav leave so little bare wall that essentially no
 * candidate was ever fully clear, so nothing ever spawned. Scoring instead of
 * rejecting means a spot is always available, and the mask below quietly hides
 * whatever part of it strays over page content.
 *
 * Rects are measured fresh each time: the shelf is React-rendered and does not
 * exist when this module first runs, and its box moves on resize and reflow.
 */
function place(w, h) {
  const rects = keepOutRects();
  const cw = w * CORE;
  const ch = h * CORE;
  const ix = (w - cw) / 2;
  const iy = (h - ch) / 2;
  const bx = w * BLEED;
  const by = h * BLEED;

  let best = null;
  let bestScore = Infinity;
  for (let i = 0; i < PLACE_ATTEMPTS; i++) {
    const left = -bx + Math.random() * (window.innerWidth - w + 2 * bx);
    const top = -by + Math.random() * (window.innerHeight - h + 2 * by);
    const score = coverage({
      left: left + ix,
      top: top + iy,
      right: left + ix + cw,
      bottom: top + iy + ch,
    }, rects);
    if (score < bestScore) {
      bestScore = score;
      best = { left, top };
      if (score === 0) break;
    }
  }
  return bestScore > MAX_COVERAGE ? null : best;
}

/* A soft-edged hole punched over each protected region.
 *
 * This, not the placement scoring, is what actually keeps apparitions off the
 * bookshelf and the masthead. Scoring only biases where they start; the mask
 * guarantees that whatever strays over protected content fades out instead of
 * crawling across the logo. Feathered rather than hard-edged so an apparition
 * dissolves at the boundary rather than being sliced off along a straight line.
 */
let maskKey = '';

function updateMask(layer) {
  const rects = keepOutRects();
  const w = window.innerWidth;
  const h = window.innerHeight;
  const key = `${w}x${h}|` + rects
    .map((r) => [r.left, r.top, r.right, r.bottom].map(Math.round).join(','))
    .join(';');
  if (key === maskKey) return;
  maskKey = key;

  const holes = rects.map((r) => {
    const x = r.left - KEEP_OUT_PAD;
    const y = r.top - KEEP_OUT_PAD;
    const rw = r.width + KEEP_OUT_PAD * 2;
    const rh = r.height + KEEP_OUT_PAD * 2;
    return `<rect x="${x.toFixed(1)}" y="${y.toFixed(1)}" width="${rw.toFixed(1)}" height="${rh.toFixed(1)}" rx="18" fill="black"/>`;
  }).join('');

  const svg =
    `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}">` +
    `<filter id="f" x="-25%" y="-25%" width="150%" height="150%">` +
    `<feGaussianBlur stdDeviation="${KEEP_OUT_FEATHER}"/></filter>` +
    `<rect width="100%" height="100%" fill="white"/>` +
    `<g filter="url(#f)">${holes}</g></svg>`;
  const url = `url("data:image/svg+xml,${encodeURIComponent(svg)}")`;
  layer.style.webkitMaskImage = url;
  layer.style.maskImage = url;
}

function spawn(layer) {
  if (layer.childElementCount >= MAX_LIVE) return;
  updateMask(layer);

  const clip = pick(CLIPS);
  const tier = pick(TIERS);
  const height = window.innerHeight * (rand(tier.height) / 100);
  const width = height * (clip.w / clip.h);
  const at = place(width, height);
  if (!at) return;

  const el = document.createElement('video');
  el.className = 'apparition';
  el.muted = true;
  el.defaultMuted = true;
  el.playsInline = true;
  el.setAttribute('playsinline', ''); // older iOS Safari reads the attribute only
  el.preload = 'auto';
  for (const [ext, type] of [['webm', 'video/webm'], ['mp4', 'video/mp4']]) {
    const source = document.createElement('source');
    source.src = `/assets/wall/${clip.name}.${ext}`;
    source.type = type;
    el.appendChild(source);
  }

  const peak = rand(tier.opacity);
  el.style.left = `${at.left}px`;
  el.style.top = `${at.top}px`;
  el.style.width = `${width}px`;
  el.style.height = `${height}px`;
  el.style.setProperty('--blur', `${rand(tier.blur).toFixed(2)}px`);
  // Mirroring doubles the pose library for free, and a little rotation keeps
  // repeat sightings of the same clip from reading as the same clip.
  el.style.transform =
    `rotate(${(Math.random() * 16 - 8).toFixed(1)}deg)` +
    (Math.random() < 0.5 ? ' scaleX(-1)' : '');

  const remove = () => {
    el.style.opacity = '0';
    setTimeout(() => el.remove(), 1200);
  };
  // Clips already open and close on flat black, so this only has to cover a
  // stalled buffer, not shape the entrance.
  el.addEventListener('playing', () => { el.style.opacity = peak.toFixed(3); }, { once: true });
  el.addEventListener('ended', remove, { once: true });
  el.addEventListener('error', () => el.remove(), { once: true });

  layer.appendChild(el);
  const playing = el.play();
  if (playing) playing.catch(() => el.remove());
}

/* Where the apparitions currently are, for anything that wants to react to one.
 *
 * Read off the live DOM rather than kept as a list this module maintains: an
 * apparition's element is removed by a timer after it fades, and a registry
 * updated by hand would drift out of step with that every time the removal path
 * changed. The elements are the source of truth, so ask them.
 *
 * Only counts apparitions that are actually showing. A clip is appended and
 * played before it fades in, and one that has not yet reached its peak opacity
 * is not visible to anybody -- being startled by it would look like the ghost
 * reacting to nothing.
 */
export function liveApparitions() {
  const layer = document.getElementById('apparitions');
  if (!layer) return [];
  const out = [];
  for (const el of layer.children) {
    if (parseFloat(el.style.opacity || '0') < 0.2) continue;
    out.push(el.getBoundingClientRect());
  }
  return out;
}

export function startWallApparitions() {
  if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return;
  if (navigator.connection && navigator.connection.saveData) return;

  const layer = document.getElementById('apparitions');
  if (!layer) return;

  let timer = null;
  // Clearing first keeps this idempotent, so a visibilitychange arriving while
  // a chain is already live cannot leave two chains running against each other.
  const schedule = () => {
    clearTimeout(timer);
    timer = setTimeout(() => {
      if (!document.hidden) spawn(layer);
      schedule();
    }, SPAWN_MIN + Math.random() * (SPAWN_MAX - SPAWN_MIN));
  };

  // Nothing in the first stretch: the page should look ordinary long enough for
  // the first apparition to be a surprise rather than part of the loading.
  timer = setTimeout(schedule, 2500);
  window.addEventListener('pagehide', () => clearTimeout(timer));

  // Throttled to a frame: resize fires continuously while a window is dragged,
  // and each distinct viewport size rebuilds and re-decodes the mask image.
  let pending = false;
  window.addEventListener('resize', () => {
    if (pending) return;
    pending = true;
    requestAnimationFrame(() => { pending = false; updateMask(layer); });
  }, { passive: true });

  document.addEventListener('visibilitychange', () => {
    if (document.hidden) {
      clearTimeout(timer);
      layer.replaceChildren();
    } else {
      schedule();
    }
  });
}
